version: '3'
services:
  app:
    image: "app:latest"
    ports:
      - 8080:8080
    depends_on:
      - redis
      - db
    links:
      - redis
      - db
    networks:
      - app-networks
  redis:
    image: "redis:alpine"
    command: redis-server --requirepass password
    expose:
      - 6379
    networks:
      - app-networks
  db:
    image: "mysql:latest"
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      # you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - 3306
    networks:
      - app-networks
networks:
  app-networks:
    driver: bridge