version: '3'
services:
  redis:
    image: "redis:5-alpine"
    restart: always
    command: redis-server --requirepass password
    expose:
      - 6379
  db:
    image: "mysql:8"
    restart: always
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: 'password'
    expose:
      - 3306
      - 33060
  app:
    image: "app:latest"
    restart: always
    ports:
      - 8080:8080